---
brand: 'GreenMud'
# bgimage: '/static/pictures/tennis/volley6.jpg'


# events
events:
  - name: 'CSS Summit'
    summary: 'Sass Map Magic'
    url: http://environmentsforhumans.com/2015/css-summit/
    date: July 7-9, 2015
    datetime: 2015-07-07
    type: talk

  - name: 'The Holes They Leave [EP Release]'
    summary: 'with Bad Luck City, Teacup Gorilla, and Coastal Wives'
    url: http://www.teacupgorilla.com/2015/06/10/ep-release/
    date: July 9, 2015
    datetime: 2015-07-09
    location: '<a href="http://www.hi-dive.com/event/864133-teacup-gorilla-denver/">Hi Dive</a> — Denver, CO'
    type: music

  - name: 'Frontend Conference Zurich'
    summary: 'Sassy Toolkits'
    url: http://frontendconf.ch
    date: Aug. 27-28, 2015
    datetime: 2015-08-28
    type: talk

  - name: 'The In-Between'
    summary: 'site-specific installation devised with Julie Rada'
    date: Sept. 6, 2015
    datetime: 2015-09-06
    type: performance

  - name: 'Clyfford Still Museum: ReTriplicate'
    summary: 'with Buntport Theater, Hoarded Stuff, and Screw Tooth'
    url: https://clyffordstillmuseum.org/
    date: Sept. 24-26, 2015
    datetime: 2015-09-24
    type: music/performance

  - name: 'SassConf 2015'
    summary: TBA
    date: Nov. 11-13, 2015
    datetime: 2015-11-11
    type: moderated discussion


# press
press:
  - quote: One of the most ambitious projects that has come across our desk recently.
    credit: Tim Wenger
    source: Colorado Music Buzz
    url: http://www.colomusicbuzz.com/eric-suzanne-drops-non-linear-novel-in-conjunction-with-teacup-gorilla/
    date: April 1, 2015
    datetime: 2015-04-01

  - quote: If you’re interested in reading Sass poetry, be sure to look at Susy’s source code!
    credit: Hugo Giraudel
    source: SitePoint
    url: http://www.sitepoint.com/my-favorite-sass-tools/
    date: April 22, 2014
    datetime: 2014-04-22

  - quote: This virtuoso creation by a talented young poet, writer, artist, typographer, programmer, and musician is a taste of things to come as new generations of digital media and code literate creators come of age.
    credit: Leonardo Flores
    source: I ♥ E-Poetry
    url: http://iloveepoetry.com/?p=2571
    date: May 2, 2013
    datetime: 2013-05-02

  - quote: I was impressed by the purest form of outrageous creation.
    credit: Judy Rose
    source: Boulder Writer’s Workshop
    url: http://www.boulderwritersworkshop.org/2013/04/17/post-obsolete-a-bww-salon/
    date: April 17, 2013
    datetime: 2013-04-17

  - quote: The album closes with “Static,” a haunting meeting of strings and electronic fuzz with vocalist/drummer Sondra Eisenstat’s lush vocals and spoken word. Eisenstat sings that there is “No voice on the radio,” and perhaps, for now, that’s true. Kingdom, though, is certainly worth a private listen at home.
    credit: Cat Carroll
    source: Onion AV Club
    url: http://www.avclub.com/
    date: August 14, 2009
    datetime: 2009-08-14

  - quote: Rarely does one encounter a production undertaken with such a tremendous amount of care and consideration.
    credit: Jack Walton
    source: South Bend Tribune
    url: http://articles.southbendtribune.com/2006-01-29/news/26962892_1_hester-darkness-athol-fugard
    date: January 29, 2006
    datetime: 2006-01-29


# interviews
interviews:
  - title: On Riding SideSaddle*
    credit: Ryo Yamaguchi
    source: Michigan Quarterly Review
    url: http://www.michiganquarterlyreview.com/2015/06/on-riding-sidesaddle-an-interview-with-eric-suzanne/
    date: June 1, 2015
    datetime: 2015-06-01

  - title: Eric Suzanne Drops Non-Linear Novel...
    credit: Tim Wenger
    source: Colorado Music Buzz
    url: http://www.colomusicbuzz.com/eric-suzanne-drops-non-linear-novel-in-conjunction-with-teacup-gorilla/
    date: April 1, 2015
    datetime: 2015-04-01

  - title: Ideas, Process, Obsolescence, and the Iterative
    credit: Mél Hogan
    source: Media Archeology Lab
    url: http://mediaarchaeologylab.com/eric-meyer-ideas-process-obsolescence-iterative-interview-mel-hogan/
    date: November 15, 2013
    datetime: 2013-11-15

  - title: Collaboration, Queer Art, and the Multi-Media Novel
    credit: Richard Wall
    source: Boulder Writers Workshop
    url: http://www.boulderwritersworkshop.org/2012/08/31/eric-meyer-discusses-collaboration-queer-art-and-his-multi-media-novel
    date: August 31, 2012
    datetime: 2012-08-31


# curiculum vite
cv:
  - name: 'WordCamp Denver'
    summary: '<a href="http://oddbooksapp.com/book/sassy-toolkits">Sassy Toolkits</a> [the WordPress way]'
    url: http://denver.wordcamp.org/2015/
    date: June 13-14, 2015
    datetime: 2015-06-13
    location: Tropicana Hotel — Las Vegas, NV
    type: talk

  - name: 'Future Insights Live'
    summary: '<a href="http://oddbooksapp.com/book/sass-map-magic">Sass Map Magic</a>'
    url: https://futureinsightslive.com/las-vegas-2015/
    date: June 1-4, 2015
    datetime: 2015-06-01
    location: Tropicana Hotel — Las Vegas, NV
    type: talk

  - name: 'Riding SideSaddle*'
    summary: 'published by <a href="http://springgunpress.com">SpringGun Press</a>'
    url: http://ridingsidesaddle.net
    date: Apr. 2, 2015
    datetime: 2015-04-02
    type: hybrid novel

  - name: 'BlendConf'
    summary: 'The Magic of Sassy Maps'
    url: https://ti.to/blendconf/blendconf2014?discount_code=ericisfabulous
    date: Sept. 11–13, 2014
    datetime: 2014-09-11
    location: Charlotte Sheraton Hotel — Charlotte, NC
    type: talk

  - name: 'PROPHETIA VETITUM MUNDI'
    summary: Screw Tooth
    url: www.screwtooth.com
    date: Aug. 2-8, 2014
    datetime: 2014-08-02
    location: Buntport Theatre – Denver, CO
    type: installation

  - name: 'Hold the Light: 2014 ELO Conference'
    summary: 'The Obsolete Book in a Post-Obsolete World'
    url: 'http://conference.eliterature.org/'
    date: June 19, 2014
    datetime: 2014-06-19
    location: University of Wisconsin-Milwaukee — Milwaukee, WI
    type: installation/performance

  - name: 'Bouldering Poets: Two Year Anniversary'
    summary: with Alan Mudd, Teacup Gorilla, and Chris Shugrue
    url: http://boulderingpoets.wordpress.com/2014/04/07/may-17-2014-two-year-anniversary/
    date: May 17, 2014
    datetime: 2014-05-17
    location: Trident Booksellers & Cafe — Boulder, CO
    type: poetry/music

  - name: Bmore Sass
    summary: 'DISusy: your layout, our math'
    url: 'http://bmore-sass.com/'
    date: April 24, 2014
    datetime: 2014-04-24
    location: Betamore — Baltimore, MD
    type: talk

  - name: CampSass
    summary: 'Show Your Work & Share Your Toys'
    url: 'http://campsass.com/'
    date: April 19, 2014
    datetime: 2014-04-19
    location: Code for America — San Francisco, CA
    type: talk

  - name: The Mixin
    summary: 'DISusy: your layout, our math'
    url: 'https://themixin.eventbrite.com/'
    date: April 16, 2014
    datetime: 2014-04-16
    location: Salesforce — San Francisco, CA
    type: talk

  - name: SassBites
    summary: Susy Grids 2.0
    url: 'bit.ly/SassBites29'
    date: March 13, 2014
    datetime: 2014-03-13
    type: podcast

  - name: NYC Sass & Compass Meetup
    summary: Organizing Sass Partials
    url: 'http://www.meetup.com/nyc-sass/events/146898452/'
    date: Nov. 2013
    datetime: 2013-11-01
    type: talk

  - name: Bad Shadow Affair
    summary: with Teacup Gorilla, Marcia Douglas, and Matt Cook
    url: http://badshadowaffair.blogspot.com/2013/11/november-16th-douglas-cook-meyer.html
    date: Nov. 2013
    datetime: 2013-10-01
    type: music/poetry
    location: Lost Lake Lounge — Denver, CO

  - name: SassConf
    summary: Show Your Work & Share Your Toys
    url: https://vimeo.com/channels/sassconf2013/86306775
    date: Oct. 2013
    datetime: 2013-10-01
    type: talk
    location: Scolastic Auditorium, NYC

  - name: Brakhage Center Media Arts Lunchtime Series
    summary: No One Wants Your Media Arts
    url: http://brakhagecenter.com/?p=932
    date: Oct. 2013
    datetime: 2013-10-01
    type: talk
    location: Colorado University, Boulder

  - name: The Operating System PRINT! vol. 3
    summary: 'Cover design & excerpts from Riding SideSaddle*'
    url: http://www.theoperatingsystem.org/layer-tennis-live-stream-print-vol-3-ole/
    date: Nov. 2013
    datetime: 2013-10-01
    type: literary journal
    location: Launchpad Brooklyn

  - name: Digital Art
    summary: with professor Erin Costello
    date: Sept. 2013
    datetime: 2013-09-01
    type: guest lecture
    location: Colorado University, Boulder

  - name: '<span class="amp">&</span>Now Festival'
    summary: Making a Small Press Work
    date: Sept. 2013
    datetime: 2013-09-01
    type: panel moderator
    location: Colorado University, Boulder

  - name: 'Media Archeology Lab / <span class="amp">&</span>Now Festival'
    summary: The Post-Obsolete Book
    url: http://mediaarchaeologylab.com/eric-meyer-2/
    date: Sept. 2013
    datetime: 2013-09-01
    type: residency/performance
    location: Colorado University, Boulder

  - name: SpringGun Journal, Issue 8
    summary: The Post-Obsolete Book
    url: http://www.springgunpress.com/issue-8-2013/
    date: Sept. 2013
    datetime: 2013-09-01
    type: literary journal

  - name: Intro to Digital Media for Humanities
    summary: with proffessor Lori Emerson
    date: Aug. 2013
    datetime: 2013-08-01
    type: guest lecture
    location: Colorado University, Boulder


# navigation
nav:
  - title: manifesto
    url: "/why/"
  - title: projects
    url: "/what/"
  - title: bio
    url: "/who/"
  - title: press
    url: "/press/"


# social
social:
  - title: email
    icon: mail
    url: "mailto:eric(put the 'at' sign here)ericsuzanne.com"
  - title: feed
    url: "http://feeds.feedburner.com/ericandmeyer/"
  - title: twitter
    url: "http://twitter.com/ericmsuzanne/"
  - title: facebook
    url: "http://facebook.com/ericmsuzanne/"
  - title: dribbble
    url: "http://dribbble.com/players/ericsuzanne/"
  - title: vimeo
    url: "http://vimeo.com/ericsuzanne"
  - title: github
    url: "http://www.github.com/ericam/"
  - title: stack overflow
    url: "http://stackoverflow.com/users/1930386/"


# colophon
colophon:
  - name: rstblog
    url: "https://github.com/mitsuhiko/rstblog/"
  - name: Python
    url: "http://www.python.org"
  - name: jQuery
    url: "http://www.jquery.com/"
  - name: Modernizr
    url: "http://www.modernizr.com/"
  - name: IcoMoon
    url: "http://keyamoon.com/icomoon/"
  - name: Susy
    url: "http://susy.oddbird.net/"
  - name: Compass
    url: "http://compass-style.org/"
  - name: Breakpoint
    url: "http://breakpoint-sass.com/"
  - name: Sass
    url: "http://sass-lang.com/"


# settings
active_modules: [pygments, tags, blog, typogrify]
author: 'Eric M Suzanne'
canonical_url: http://andmeyer.com/
output_folder: ../output
template_path: ../templates
modules:
  pygments:
    style: borland
  blog:
    index_url: /
