---
brand: 'GreenMud'
bgimage: '/static/pictures/tennis/volley6.jpg'


# events
events:
  - title: 'Susy 2.0'
    forum: Bmore Sass
    url: http://bmore-sass.com/
    date: April 17, 2014
    location: online


# curiculum vite
cv:
  - title: Organizing Sass Partials
    title-url: 'http://ericsuzanne.com/pres/sass-partials/'
    forum: NYC Sass & Compass Meetup
    forum-url: 'http://www.meetup.com/nyc-sass/events/146898452/'
    date: Nov. 2013
    role: featured speaker
    type: meetup
    location: online

  - forum: Bad Shadow Affair
    date: Nov. 2013
    role: poet & musician
    type: reading series
    with: Teacup Gorilla, Marcia Douglas, and Matt Cook
    location: Lost Lake Lounge, Denver

  - title: Show Your Work & Share Your Toys
    forum: SassConf
    date: Oct. 2013
    role: featured speaker
    type: conference
    location: Scolastic Auditorium, NYC

  - title: No One Wants Your Media Arts
    forum: Brakhage Center Media Arts Lunchtime Series
    date: Oct. 2013
    role: featured speaker
    type: lecture series
    location: Colorado University, Boulder

  - forum: The Operating System PRINT! vol. 3
    date: Nov. 2013
    role: writer & designer
    type: literary journal & reading series
    notes: 'cover art & excerpts from <em>Variations on Riding Side Saddle</em>'
    location: Launchpad Brooklyn

  - forum: Digital Art
    date: Sept. 2013
    role: guest lecture
    type: class
    with: Prof. Erin Costello
    location: Colorado University, Boulder

  - title: Making a Small Press Work
    date: Sept. 2013
    role: moderator
    forum: '&Now Festival'
    type: conference
    location: Colorado University, Boulder

  - title: The Post-Obsolete Book
    date: Sept. 2013
    role: resident artist
    forum: Media Archeology Lab
    type: residency/performance
    location: Colorado University, Boulder
    notes: 'In conjunction with the &Now Festival'

  - title: The Post-Obsolete Book
    forum: SpringGun Journal, Issue 8
    date: Sept. 2013
    role: digital artist
    type: literary journal

  - forum: Intro to Digital Media for Humanities
    date: Aug. 2013
    role: guest lecture
    location: Colorado University, Boulder
    with: Prof. Lori Emerson


# navigation
nav:
  - title: manifesto
    url: "/why/"
  - title: projects
    url: "/what/"
  - title: bio
    url: "/who/"


# social
social:
  - title: email
    icon: mail
    url: "mailto:eric(put the 'at' sign here)ericsuzanne.com"
  - title: feed
    url: "http://feeds.feedburner.com/ericandmeyer/"
  - title: twitter
    url: "http://twitter.com/ericmsuzanne/"
  - title: facebook
    url: "http://facebook.com/ericmsuzanne/"
  - title: dribbble
    url: "http://dribbble.com/players/ericsuzanne/"
  - title: vimeo
    url: "http://vimeo.com/ericsuzanne"
  - title: github
    url: "http://www.github.com/ericam/"
  - title: stack overflow
    url: "http://stackoverflow.com/users/1930386/"


# colophon
colophon:
  - name: rstblog
    url: "https://github.com/mitsuhiko/rstblog/"
  - name: Python
    url: "http://www.python.org"
  - name: jQuery
    url: "http://www.jquery.com/"
  - name: Modernizr
    url: "http://www.modernizr.com/"
  - name: IcoMoon
    url: "http://keyamoon.com/icomoon/"
  - name: Susy
    url: "http://susy.oddbird.net/"
  - name: Compass
    url: "http://compass-style.org/"
  - name: Breakpoint
    url: "http://breakpoint-sass.com/"
  - name: Sass
    url: "http://sass-lang.com/"


# settings
active_modules: [pygments, tags, blog, typogrify]
author: 'Eric M Suzanne'
canonical_url: http://andmeyer.com/
output_folder: ../output
template_path: ../templates
modules:
  pygments:
    style: borland
  blog:
    index_url: /
